name: Update Requirements

on:
  push:
    branches:
      - main # Trigger on push to the main branch
  pull_request:
    branches:
      - main

jobs:
  update-requirements:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install pip-tools
      run: |
        python -m pip install --upgrade pip
        pip install pip-tools

    - name: Compile requirements.txt
      run: |
        pip-compile requirements.in

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add requirements.txt
        git commit -m 'Update requirements.txt'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}