name: Update Requirements

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update-requirements:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' # Replace with your Python version

    - name: Install pipreqs
      run: |
        python -m pip install --upgrade pip
        pip install pipreqs

    - name: Generate requirements.txt
      run: |
        pipreqs . --force

    - name: Commit and push updated requirements.txt
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add requirements.txt
        git commit -m "Update requirements.txt"
        git push https://${{ secrets.PAT }}@github.com/oneping-1/MLB.git HEAD:main
